"""Turns retrieved RAG chunks into a natural-language answer, via Sarvam's chat completion API --
the same LLM/pattern already used by summary_service.py and normalization_service.py.

Citations are NEVER generated by this service or the LLM -- they're built separately, directly
from chunk metadata, by ask_janmitra_service.py (see that module). This service's prompt (see
prompts/ask_janmitra_system_prompt.txt) explicitly instructs the model not to write its own
source list, specifically to prevent an LLM from inventing a URL/phone number that sounds
plausible but isn't in the retrieved context.

Graceful degradation, not a hard failure: if the LLM is unconfigured or the call fails, this
falls back to a simple template built directly from the retrieved chunks' own text -- Ask
Sarthi must keep working (with real, sourced content, just not LLM-polished prose) even
without a working LLM connection, matching this codebase's existing pattern
(normalization_service.py falls back to the original text the same way).
"""

import logging

import httpx
from sarvamai import SarvamAI

from backend.config import get_prompt, settings

logger = logging.getLogger(__name__)


class AnswerGenerationService:
    def __init__(self) -> None:
        self._client: SarvamAI | None = None
        if settings.LLM_API_KEY:
            # See config.py's SARVAM_CONNECT_TIMEOUT_SECONDS docstring: this reasoning-model call
            # needs a generous read timeout (legitimate slow-but-working answers shouldn't be cut
            # off), but still fails fast on a genuinely dead connection.
            timeout = httpx.Timeout(
                connect=settings.SARVAM_CONNECT_TIMEOUT_SECONDS,
                read=settings.SARVAM_REASONING_READ_TIMEOUT_SECONDS,
                write=settings.SARVAM_REASONING_READ_TIMEOUT_SECONDS,
                pool=settings.SARVAM_REASONING_READ_TIMEOUT_SECONDS,
            )
            self._client = SarvamAI(api_subscription_key=settings.LLM_API_KEY, timeout=timeout)
        else:
            logger.warning("LLM_API_KEY is not set; Ask Sarthi will fall back to raw excerpts, not LLM-generated prose.")

    def generate(
        self, question: str, context_chunks: list[str], language_name: str,
        context_labels: list[str] | None = None,
    ) -> tuple[str, bool]:
        """Returns (answer_text, was_llm_generated). was_llm_generated=False means the fallback
        template was used (LLM unconfigured or the call failed) -- callers/tests can assert on
        this rather than guessing from the text shape.

        `context_labels`, if given, must be the same length as `context_chunks` -- one short
        "VERIFIED | Topic: ..." label per chunk (see rag_retriever.chunk_context_label), shown to
        the LLM alongside that chunk's content so it can tell a topically-mismatched-but-
        same-category record apart from one that actually answers the question (see that
        function's own docstring for the live Bhubaneswar case this closes). Optional and
        defaults to None so any caller not yet passing it keeps behaving exactly as before.
        Deliberately NOT folded into `context_chunks` itself: `_fallback_answer` echoes a chunk's
        content verbatim when no LLM is available, and must never leak this internal label into a
        citizen-facing answer."""
        if context_labels:
            prompt_chunks = [f"[{label}]\n{chunk}" for label, chunk in zip(context_labels, context_chunks)]
        else:
            prompt_chunks = context_chunks
        context = "\n\n---\n\n".join(prompt_chunks)

        if self._client is None:
            return self._fallback_answer(context_chunks), False

        try:
            system_prompt = get_prompt("ask_janmitra_system_prompt.txt")
            prompt_template = get_prompt("ask_janmitra_answer_prompt.txt")
            prompt = prompt_template.format(question=question, context=context, language_name=language_name)

            response = self._client.chat.completions(
                model=settings.LLM_MODEL,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=settings.LLM_MAX_TOKENS,
                reasoning_effort="low",
            )
            choice = response.choices[0]
            content = choice.message.content
            if not content or not content.strip():
                logger.warning(
                    "Ask Sarthi answer generation returned no content (finish_reason=%s); falling back to raw excerpts.",
                    choice.finish_reason,
                )
                return self._fallback_answer(context_chunks), False
            return content.strip(), True
        except Exception as exc:
            logger.warning("Ask Sarthi answer generation failed, falling back to raw excerpts: %s", exc, exc_info=True)
            return self._fallback_answer(context_chunks), False

    @staticmethod
    def _fallback_answer(context_chunks: list[str]) -> str:
        if not context_chunks:
            return "I don't have information on this yet."
        # Plain, honest fallback -- the retrieved text itself, not a paraphrase, so nothing is
        # invented even when no LLM is available to phrase it more naturally.
        return context_chunks[0]
