"""Turns retrieved RAG chunks into a natural-language answer, via Sarvam's chat completion API --
the same LLM/pattern already used by summary_service.py and normalization_service.py.

Citations are NEVER generated by this service or the LLM -- they're built separately, directly
from chunk metadata, by ask_janmitra_service.py (see that module). This service's prompt (see
prompts/ask_janmitra_system_prompt.txt) explicitly instructs the model not to write its own
source list, specifically to prevent an LLM from inventing a URL/phone number that sounds
plausible but isn't in the retrieved context.

Graceful degradation, not a hard failure: if the LLM is unconfigured or the call fails, this
falls back to a simple template built directly from the retrieved chunks' own text -- Ask
Sarthi must keep working (with real, sourced content, just not LLM-polished prose) even
without a working LLM connection, matching this codebase's existing pattern
(normalization_service.py falls back to the original text the same way).
"""

import logging

from sarvamai import SarvamAI

from backend.config import get_prompt, settings

logger = logging.getLogger(__name__)


class AnswerGenerationService:
    def __init__(self) -> None:
        self._client: SarvamAI | None = None
        if settings.LLM_API_KEY:
            self._client = SarvamAI(api_subscription_key=settings.LLM_API_KEY)
        else:
            logger.warning("LLM_API_KEY is not set; Ask Sarthi will fall back to raw excerpts, not LLM-generated prose.")

    def generate(self, question: str, context_chunks: list[str], language_name: str) -> tuple[str, bool]:
        """Returns (answer_text, was_llm_generated). was_llm_generated=False means the fallback
        template was used (LLM unconfigured or the call failed) -- callers/tests can assert on
        this rather than guessing from the text shape."""
        context = "\n\n---\n\n".join(context_chunks)

        if self._client is None:
            return self._fallback_answer(context_chunks), False

        try:
            system_prompt = get_prompt("ask_janmitra_system_prompt.txt")
            prompt_template = get_prompt("ask_janmitra_answer_prompt.txt")
            prompt = prompt_template.format(question=question, context=context, language_name=language_name)

            response = self._client.chat.completions(
                model=settings.LLM_MODEL,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=settings.LLM_MAX_TOKENS,
                reasoning_effort="low",
            )
            choice = response.choices[0]
            content = choice.message.content
            if not content or not content.strip():
                logger.warning(
                    "Ask Sarthi answer generation returned no content (finish_reason=%s); falling back to raw excerpts.",
                    choice.finish_reason,
                )
                return self._fallback_answer(context_chunks), False
            return content.strip(), True
        except Exception as exc:
            logger.warning("Ask Sarthi answer generation failed, falling back to raw excerpts: %s", exc, exc_info=True)
            return self._fallback_answer(context_chunks), False

    @staticmethod
    def _fallback_answer(context_chunks: list[str]) -> str:
        if not context_chunks:
            return "I don't have information on this yet."
        # Plain, honest fallback -- the retrieved text itself, not a paraphrase, so nothing is
        # invented even when no LLM is available to phrase it more naturally.
        return context_chunks[0]
