import { useEffect, useState } from "react";
import { useAuth } from "../lib/auth";
import { useUiLang } from "../lib/uiLang";
import { t } from "../lib/i18n";
import { api, ApiError, type ComplaintReport } from "../lib/api";
import ComplaintReportView from "./ComplaintReportView";
import DownloadReportButton from "./DownloadReportButton";

/** "View Report" -- only ever rendered by a caller that already knows the complaint is
 * RESOLVED; the backend independently re-enforces this (404 if it isn't, surfaced here as a
 * plain error state rather than a fake report). Loads real data via GET
 * /complaints/{id}/report -- never generated by an LLM, see complaint_report_service.py. */
export default function ReportModal({ complaintId, onClose }: { complaintId: number; onClose: () => void }) {
  const { token } = useAuth();
  const { lang } = useUiLang();
  const [report, setReport] = useState<ComplaintReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!token) return;
    setLoading(true);
    setError(null);
    api
      .getComplaintReport(token, complaintId)
      .then(setReport)
      .catch((err) => setError(err instanceof ApiError ? err.message : t(lang, "worker.detail.reportLoadFailed")))
      .finally(() => setLoading(false));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token, complaintId]);

  return (
    <div className="overlay" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal" style={{ maxWidth: 520 }}>
        <div className="modal-head">
          <h3 className="display">{t(lang, "worker.viewReport")}</h3>
          <button className="x" aria-label={t(lang, "common.close")} onClick={onClose}>
            ✕
          </button>
        </div>

        {loading && <p style={{ color: "var(--ink-2)", fontSize: 13 }}>{t(lang, "common.loading")}</p>}
        {error && <div className="banner-error">{error}</div>}
        {!loading && report && <ComplaintReportView report={report} />}

        <div className="modal-actions">
          <button type="button" className="btn btn-ghost" onClick={onClose}>
            {t(lang, "common.close")}
          </button>
          {report && <DownloadReportButton complaintId={complaintId} className="btn btn-primary" />}
        </div>
      </div>
    </div>
  );
}
