import { useEffect, useState } from "react";
import { useAuth } from "../lib/auth";
import { useUiLang } from "../lib/uiLang";
import { t } from "../lib/i18n";
import { api, ApiError } from "../lib/api";
import ShareReportButton from "./ShareReportButton";
import { useModalA11y } from "../lib/useModalA11y";

/** "View Report" -- only ever rendered by a caller that already knows the complaint is
 * RESOLVED; the backend independently re-enforces this (404 if it isn't, surfaced here as a
 * plain error state rather than a fake report). Embeds the same PDF (GET
 * /complaints/{id}/report/download, never generated by an LLM -- see
 * complaint_report_service.py) via the browser's built-in PDF viewer. No title text or Download
 * button in the header -- just an icon-only Share action and close; Download lives as its own
 * separate button elsewhere on the page. */
export default function ReportModal({ complaintId, onClose }: { complaintId: number; onClose: () => void }) {
  const { token } = useAuth();
  const { lang } = useUiLang();
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!token) return;
    let objectUrl: string | null = null;
    let cancelled = false;
    setLoading(true);
    setError(null);
    setPdfUrl(null);
    api
      .downloadComplaintReport(token, complaintId, lang)
      .then(({ blob }) => {
        if (cancelled) return;
        objectUrl = URL.createObjectURL(blob);
        setPdfUrl(objectUrl);
      })
      .catch((err) => {
        if (cancelled) return;
        setError(err instanceof ApiError ? err.message : t(lang, "worker.detail.reportLoadFailed"));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
      if (objectUrl) URL.revokeObjectURL(objectUrl);
    };
  }, [token, complaintId, lang]);

  const modalRef = useModalA11y(onClose);

  return (
    <div className="overlay" style={{ padding: 8 }} onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div
        ref={modalRef}
        className="modal"
        // .modal's default padding/max-height/overflow-y (meant for short-content dialogs) would
        // inset the grey PDF area with a white margin on every side and risk a second, competing
        // scrollbar -- overridden here to zero padding + hidden overflow so the grey area reaches
        // this modal's own rounded corners edge-to-edge, same as the reference this was matched to.
        // Narrower than a wide desktop window, but tall -- the report itself is a portrait A4
        // page, so a very wide modal just left the native PDF viewer's toolbar spanning far more
        // width than the page needs, making its dark bar look disproportionately heavy.
        style={{ maxWidth: "94vw", width: "860px", height: "99vh", maxHeight: "99vh", padding: 0, overflow: "hidden", display: "flex", flexDirection: "column" }}
        role="dialog"
        aria-modal="true"
        aria-label={t(lang, "worker.viewReport")}
        tabIndex={-1}
      >
        {/* No title text and no Download button here (Download lives on the page itself) -- just
            the icon-only Share action plus close, kept small and out of the way of the report. */}
        <div className="modal-head" style={{ flexShrink: 0, margin: 0, padding: "8px 12px", borderBottom: "1px solid var(--line)", justifyContent: "flex-end", alignItems: "center", gap: 8 }}>
          {pdfUrl && <ShareReportButton complaintId={complaintId} className="icon-pill-btn" iconOnly />}
          <button className="x" aria-label={t(lang, "common.close")} onClick={onClose}>
            ✕
          </button>
        </div>

        {loading && <p style={{ color: "var(--ink-2)", fontSize: 13, padding: "0 20px" }}>{t(lang, "common.loading")}</p>}
        {error && <div className="banner-error" style={{ margin: "0 20px" }}>{error}</div>}
        {!loading && pdfUrl && (
          // A light-grey (var(--surface-2)) container behind the iframe, filling the rest of the
          // modal edge-to-edge -- matching how a native PDF viewer is normally framed. The
          // browser's own page margin around the document reads as a stark, boxed-in "border"
          // against a plain white background, but blends in against a surface that's already a
          // shade off white.
          <div style={{ flex: 1, minHeight: 0, background: "var(--surface-2)" }}>
            <iframe
              src={pdfUrl}
              title={t(lang, "worker.viewReport")}
              style={{ width: "100%", height: "100%", border: "none" }}
            />
          </div>
        )}
      </div>
    </div>
  );
}
